steps:
  - name: "gcr.io/cloud-builders/mvn"
    args: ["clean install", "github.com/trekslab/gcp-cd-codelab"]
    env: ["PROJECT_ROOT=github.com/trekslab/gcp-cd-codelab"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/silken-apex-212008/gcp-cd-codelab:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/silken-apex-212008/gcp-cd-codelab:$REVISION_ID"
